# Algorithms

In [2]:
import numpy as np

rng = np.random.default_rng(seed=77)

## Algorithm 1

In [7]:
import alg1

N = 6
d = 8
Sigma = np.eye(d)
theta = (rng.standard_normal(size = d))[:, np.newaxis]
epsilon = 6.767

X, y = alg1.algorithm(N = N, d = d, Sigma = Sigma, theta = theta, epsilon = epsilon)

print(X)
print(y)

[[ 0.585 -0.336  2.391 -1.486  1.106 -0.388 -0.315  1.917]
 [-1.661 -0.75  -0.377  1.863  0.533  0.652 -1.824 -0.388]
 [ 1.126 -0.393 -0.326  0.853 -1.761 -1.445 -0.055 -0.696]
 [-0.554  0.193 -0.928 -0.147  0.485  1.086  1.618  0.456]
 [-0.671  1.124  0.247  0.371 -0.464  0.401  0.911 -0.934]
 [ 1.174  0.162 -1.007 -1.455  0.102 -0.305 -0.336 -0.354]]
[[ -4.074]
 [ -6.405]
 [ 25.044]
 [-16.425]
 [  3.676]
 [ -1.816]]


## Algorithm 2

In [9]:
import alg2

U, S, Vt = np.linalg.svd(X)
V = Vt.T
lambda_0 = 1  
delta = 10 ** -4

lambda_, mse_value = ModelOptReg(S, V, theta, epsilon, lambda_0, delta)
print(lambda_)
print(mse_value)

NameError: name 'ModelOptReg' is not defined

## Algorithm 3

## Algorithm 4

## Algorithm 5