# Algorithms

In [1]:
import numpy as np

rng = np.random.default_rng(seed=77)

## Algorithm 1

In [2]:
import alg1

N = 6
d = 8
Sigma = np.eye(d)
theta = (rng.standard_normal(size = d))[:, np.newaxis]
epsilon = 6.767

X, y = alg1.algorithm(N = N, d = d, Sigma = Sigma, theta = theta, epsilon = epsilon)

print(X)
print(y)

[[ 0.585 -0.336  2.391 -1.486  1.106 -0.388 -0.315  1.917]
 [-1.661 -0.75  -0.377  1.863  0.533  0.652 -1.824 -0.388]
 [ 1.126 -0.393 -0.326  0.853 -1.761 -1.445 -0.055 -0.696]
 [-0.554  0.193 -0.928 -0.147  0.485  1.086  1.618  0.456]
 [-0.671  1.124  0.247  0.371 -0.464  0.401  0.911 -0.934]
 [ 1.174  0.162 -1.007 -1.455  0.102 -0.305 -0.336 -0.354]]
[[ 13.415]
 [ -9.256]
 [ 13.147]
 [-14.985]
 [  0.321]
 [ -2.643]]


## Algorithm 2

In [8]:
import alg2

U, S, Vt = np.linalg.svd(X)
V = Vt.T
lambda_0 = 1  
delta = 10 ** -4

lambda_, mse_value = alg2.ModelOptReg(S, V, theta, epsilon, lambda_0, delta)
print(lambda_)
print(mse_value)

13.296593472209377
58.06635623334377


In [ ]:
# lambdas = np.logspace(-4, 2, 1000)

# mse_values = np.array([
#     alg2.mse(S, V, theta, lam, epsilon)
#     for lam in lambdas
# ])

# idx = np.argmin(mse_values)

# print("grid-search lambda:", lambdas[idx])
# print("grid-search MSE:", mse_values[idx])

# print("fixed-point lambda:", lambda_)
# print("fixed-point MSE:", mse_value)

# print("lambda =", lambda_)
# print("epsilon^2 H(lambda) =", epsilon**2 * alg2.H(S, V, theta, lambda_))
# print("difference =", abs(lambda_ - epsilon**2 * alg2.H(S, V, theta, lambda_)))

## Algorithm 3

## Algorithm 4

## Algorithm 5